#!/usr/bin/env bash

app_dir_path='/usr/share/applications'
config_dir_path='/etc/arkane/application-cleaner'

cd "$config_dir_path"

for file in *; do
	cd "$config_dir_path"

	source "./$file"
	declare source_exit_code="$?"

	if [[ ! $source_exit_code -eq 0 ]]; then
		printf "Failed to source $file in $config_dir_path\n"
	elif [[ ! -v target || ! -v contain ]]; then
		printf "Not all required variables are set in $file\n"
	else
		cd "$app_dir_path"

		grep -qs "$contain" "$target"
		declare grep_exit_code="$?"

		if [[ $grep_exit_code -eq 0 ]]; then
			printf "Skipping $target, file is already configured properly\n"
		elif [[ $grep_exit_code -eq 1 ]]; then

			printf "$contain" >> $target

			if [[ ! $? -eq 0 ]]; then
				printf "Failed to append $contain to $file, this might be a permission issue\n"
			fi

		elif [[ $grep_exit_code -eq 2 ]]; then
			printf "Could not find $target, file does not exist\n"
		else
			printf "Encountered an unknown error with $file\n"
		fi
	fi
done
