#!/usr/bin/env bash
#
# Licensed under the BSD-3-Clause license, 2023, Arkane Linux

app_dir_path='/usr/share/applications'
config_dir_path='/etc/arkane/application-cleaner'

cd $config_dir_path

for file in *; do

	source $config_dir_path/$file

	if [[ ! -v target || ! -v contain ]]; then
		printf "Not all required variables are set in $file, skipping...\n"
	else
		cd $app_dir_path

		if ! grep -qs "$contain" "$target"; then
			printf $contain >> $target

			if [[ ! $? -eq 0 ]]; then
				printf "Failed to append $contain to $file, this might be a permission issue\n"
			fi
		fi

		if [[ ! -z $not_contain ]]; then
			grep -sv "$not_contain" "$target" >> "$target.tmp"
			mv "$target.tmp" "$target"
		fi

		unset contain
		unset target
		unset not_contain

	fi
done

exit 0
