#!/usr/bin/env bash
#
# Licensed under the BSD-3-Clause license, 2023, Arkane Linux

app_dir_path='/usr/share/applications'
config_dir_path='/etc/arkane/application-cleaner'

cd "$config_dir_path"

for file in *; do
	cd "$config_dir_path"

	source "./$file"
	declare source_exit_code="$?"

	if [[ ! $source_exit_code -eq 0 ]]; then
		printf "Failed to source $file in $config_dir_path\n"
	elif [[ ! -v target || ! -v contain ]]; then
		printf "Not all required variables are set in $file\n"
	else
		cd "$app_dir_path"

		grep -qs "$contain" "$target"
		declare grep_exit_code="$?"

		if [[ $grep_exit_code -eq 1 ]]; then

			printf "$contain" >> $target

			if [[ ! $? -eq 0 ]]; then
				printf "Failed to append $contain to $file, this might be a permission issue\n"
			fi
		fi
	fi
done
